routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'TopicsController@index')->name('root');

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');


// User Rooutes...
Route::resource('users', 'UsersController', ['only' => ['show', 'edit', 'update']]);

// Topic Routes...
Route::resource('topics', 'TopicsController', ['only' => ['index', 'create', 'store', 'update', 'edit', 'destroy']]);
Route::get('topics/{topic}/{slug?}', 'TopicsController@show')->name('topics.show');
Route::post('upload_image', 'TopicsController@uploadImage')->name('topics.upload_image');

// Category Routes
Route::resource('categories','CategoriesController', ['only' => ['show']]);

// Reply Routes
Route::resource('replies', 'RepliesController', ['only' => ['store', 'destroy']]);

// Notification Routes
Route::resource('notifications', 'NotificationsController', ['only' => ['index']]);

Route::get('permission-denied', 'PagesController@permissionDenied')->name('permission-denied');

app/Models/User.php
<?php

namespace App\Models;

use App\Models\Traits\ActiveUserHelper;
use App\Models\Traits\LastActivedAtHelper;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;

/**
 * Class User
 * @package App\Models
 *
 * @property integer $id
 * @property string  $name
 * @property string  $email
 * @property string  $password
 * @property string  $remember_token
 * @property string  $created_at
 * @property string  $updated_at
 * @property string  $avatar
 * @property string  $introduction
 * @property integer $notification_count
 * @property string  $last_actived_at
 *
 * @property array   $attributes
 *
 * @property Topic   $topics
 * @property Reply   $replies
 */
class User extends Authenticatable
{
    use Notifiable {notify as protected laravelNotify; }
    use HasRoles; // 让我们获取到扩展包提供的所有权限和角色的操作方法
    use ActiveUserHelper;
    use LastActivedAtHelper;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'avatar', 'introduction',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * 修改器：后台设置密码时，对密码做加密处理
     *
     * @author : wuliang@koudailc.com
     *
     * @param $value
     *
     */
    public function setPasswordAttribute($value)
    {
        // 如果值的长度等于 60，即认为是已经做过加密的情况
        if (strlen($value) != 60) {

            // 不等于 60，做密码加密处理
            $value = bcrypt($value);
        }

        $this->attributes['password'] = $value;
    }

    /**
     * 修改器：后台上传头像是，补全url
     *
     * @author : wuliang@koudailc.com
     *
     * @param $path
     */
    public function setAvatarAttribute($path)
    {
        // 如果不是 `http` 子串开头，那就是从后台上传的，需要补全 URL
        if ( ! starts_with($path, 'http')) {

            // 拼接完整的 URL
            $path = config('app.url') . "/uploads/images/avatars/$path";
        }

        $this->attributes['avatar'] = $path;
    }

    /**
     * 用户操作权限判断
     *
     * @author: wuliang@koudailc.com
     *
     * @param $model
     *
     * @return bool
     */
    public function isAuthorOf($model)
    {
        return $this->id == $model->user_id;
    }

    /**
     * 获取用户发布的话题信息
     *
     * @author: wuliang@koudailc.com
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function topics()
    {
        return $this->hasMany(Topic::class);
    }

    /**
     * 获取用户所有的回复
     *
     * @author: wuliang@koudailc.com
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function replies()
    {
        return $this->hasMany(Reply::class);
    }

    /**
     * 重写通知方法
     *
     * @author: wuliang@koudailc.com
     *
     * @param $instance
     *
     * @return bool
     */
    public function notify($instance)
    {
        // 如果要通知的人是当前登录用户，就不必通知了
        if ($this->id == \Auth::id()) {
            return true;
        }

        // 增加用户收到的未读通知数
        $this->increment('notification_count');

        // 调用系统通知方法
        $this->laravelNotify($instance);

        return true;
    }

    /**
     * 清空未读通知数 && 将通知状态置为已读
     *
     * @author : wuliang@koudailc.com
     * @return mixed
     */
    public function markAsRead()
    {
        $this->notification_count = 0;
        $this->save();

        $this->unreadNotifications->markAsRead();
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\Handlers\ImageUploadHandler;
use App\Http\Requests\UserRequest;
use App\Models\User;

class UsersController extends Controller
{
    /**
     * UsersController constructor.
     */
    public function __construct()
    {
        $this->middleware('auth', ['except' => ['show']]);
    }

    /**
     * 用户个人信息展示页面
     *
     * @author: wuliang@koudailc.com
     *
     * @param \App\Models\User $user
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show(User $user)
    {
        return view('users.show', compact('user'));
    }

    /**
     * 用户个人信息编辑页面
     *
     * @author: wuliang@koudailc.com
     *
     * @param \App\Models\User $user
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(User $user)
    {
        // 授权判断
        $this->authorize('update', $user);

        return view('users.edit', compact('user'));
    }

    /**
     * 用户个人信息修改数据保存
     *
     * @author: wuliang@koudailc.com
     *
     * @param \App\Http\Requests\UserRequest   $request
     * @param \App\Handlers\ImageUploadHandler $uploadHandler
     * @param \App\Models\User                 $user
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(UserRequest $request, ImageUploadHandler $uploadHandler, User $user)
    {
        // 授权判断
        $this->authorize('update', $user);

        $data = $request->all();

        if ($avatar = $request->file('avatar')) {
            $result = $uploadHandler->save($avatar, 'avatars', $user->id, 600);
            $data['avatar'] = $result['path'] ?: '';
        }

        $user->update($data);

        return redirect(route('users.show', $user->id))->with('success', '个人资料更新成功');
    }
}

resources/views/users/_replies.blade.php
@if (count($replies) > 0)
    <ul class="list-group">
        @foreach($replies as $index => $reply)
            <li class="list-group-item">
                <a href="{{ $reply->topic->link(['#reply' . $reply->id]) }}">{{ $reply->topic->title }}</a>

                <div class="reply-content" style="margin: 6px 0;">
                    {!! $reply->content !!}
                </div>

                <div class="meta">
                    <span class="glyphicon glyphicon-time" aria-hidden="true"></span> 回复于 {{ $reply->created_at->diffForHumans() }}
                </div>
            </li>
        @endforeach
    </ul>
@else
    <div class="empty-block">暂无数据 ~_~ </div>
@endif

{{--分页--}}
{{--我们使用了 URL 中的 tab 请求参数对话题列表进行区分，分页中 appends() 方法可以使 URI 中的请求参数得到继承--}}
{!! $replies->appends(Request::except('page'))->render() !!}

resources/views/users/_topics.blade.php
@if(count($topics))
    <ul class="list-group">
        @foreach($topics as $topic)
            <li class="list-group-item">
                <a href="{{ $topic->link() }}">{{ $topic->title }}</a>
                <span class="meta pull-right">
                    {{ $topic->reply_count }} 回复
                    <span> ⋅ </span>
                    {{ $topic->created_at->diffForHumans() }}
                </span>
            </li>
        @endforeach
    </ul>
@else
    <div class="empty-block">暂无数据 ~_~ </div>
@endif

{{--分页--}}
{!! $topics->render() !!}

resources/views/users/edit.blade.php
@extends('layouts.app')
@section('title', $user->name . '修个个人信息')

@section('content')
    <div class="container">
        <div class="col-md-10 col-md-offset-1 panel panel-default">

            <div class="panel-heading">
                <h4>
                    <i class="glyphicon glyphicon-edit">编辑个人资料</i>
                </h4>
            </div>

            @include('common.error')

            <div class="panel-body">
                <form action="{{ route('users.update', $user->id) }}" method="POST" accept-charset="utf-8" enctype="multipart/form-data">
                    <input type="hidden" name="_method" value="PUT">
                    <input type="hidden" name="_token" value="{{ csrf_token() }}">

                    <div class="form-group">
                        <label for="name-field">用户名：</label>
                        <input id="name-field" type="text" name="name" value="{{ old('name', $user->name) }}" class='form-control'>
                    </div>

                    <div class="form-group">
                        <label for="email-field">邮 箱：</label>
                        <input id="email-field" type="email" name="email" value="{{ old('email', $user->email) }}" class="form-control">
                    </div>

                    <div class="form-group">
                        <label for="introduction-field">个人简介：</label>
                        <textarea id="introduction-field" name="introduction" rows="3" class="form-control">{{ old('introduction', $user->introduction) }}</textarea>
                    </div>

                    <div class="form-group">
                        <label for="avatar-field" class="aratar-label">用户头像：</label>
                        <input id="avatar-field" type="file" name="avatar">

                        @if ($user->avatar)
                            <img class="thumbnail img-responsive" src="{{ $user->avatar }}" alt="用户头像" width="200px">
                        @endif
                    </div>

                    <div class="well well-sm">
                        <button type="submit" class="btn btn-primary btn-block">保 存</button>
                    </div>

                </form>
            </div>

        </div>
    </div>
@stop

resources/views/users/show.blade.php
@extends('layouts.app')
@section('title', $user->name. '个人中心')

@section('content')
    <div class="row">

        <div class="col-lg-3 co-md-3 hidden-sm hidden-xs user-info">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="media">
                        <div align="center">
                            <img class="thumbnail img-responsive" src="{{ $user->avatar }}" alt="用户头像" width="300px" height="300px">
                        </div>

                        <div class="media-body">
                            <hr>
                            <strong>个人简介</strong>
                            <p>{{ $user->introduction }}</p>
                            <hr>
                            <strong>注册于</strong>
                            <p>{{ $user->created_at->diffForHumans() }}</p>
                            <hr>
                            <strong>最后活跃</strong>
                            <p>{{ $user->last_actived_at->diffForHumans() }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <span>
                        <h1 class="panel-title pull-left" style="font-size: 30px;">{{ $user->name }} <small>{{ $user->email }}</small></h1>
                    </span>
                </div>
            </div>
            <hr>

            {{--用户发布的内容--}}
            <div class="panel panel-default">
                <div class="panel-body">
                    <ul class="nav nav-tabs">
                        <li class="{{ active_class(if_query('tab', null)) }}">
                            <a href="{{ route('users.show', [$user->id]) }}">Ta 的话题</a>
                        </li>
                        <li class="{{ active_class(if_query('tab', 'replies')) }}">
                            <a href="{{ route('users.show', [$user->id, 'tab' => 'replies']) }}">Ta 的回复</a>
                        </li>
                    </ul>

                    @if (if_query('tab', 'replies'))
                        @include('users._replies', ['replies' => $user->replies()->with('topic')->recent()->paginate(5)])
                    @else
                        @include('users._topics', ['topics' => $user->topics()->recent()->paginate(5)])
                    @endif
                </div>
            </div>
        </div>

    </div>
@stop